# Generated by Django 2.2.12 on 2020-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Nauczyciel'),
        ),
    ]
